extensions = ["md"]
timeout = 5 # in seconds
header = { "accept" = "text/html" }
accept = [
    "200",
    "429",
    "502", # it's ok if the backend is down during the scan
]
exclude = [
    '^https://pki\.infineon\.com',
    '^https://www\.st\.com',
    '^https://software\.intel\.com',
    '^https://(.*\.)?github(usercontent)?\.(com|io)',
]
